 /******************************************************************************
 *
 * Module: ULTRASONIC SENSOR
 *
 * File Name: ultrasonic_sensor.h
 *
 * Description: Header file for the ULTRASONIC SENSOR driver
 *
 * Author: Basma Ashraf Kamel
 *
 *
 *
 *******************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TRIGGER_PIN PIN5_ID

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/

/*
 * [Description]: initializes the ultrasonic sensor by:
 * 1- Initialize the ICU.
 * 2- Set the callback function.
 * 3- Setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void);

/*
 * [Description]: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * [Description]:
 * 1- Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2- Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * [Description]:
 * 1- This is the call back function called by the ICU driver.
 * 2- This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_SENSOR_H_ */
